Smurf.exe: main.o argsNode.o assignmentNode.o astNode.o Binding.o codeNode.o customAST.o decNode.o fnCallNode.o fnDecNode.o func.o identifierNode.o ifNode.o Interpreter.o intNode.o opNode.o printNode.o programNode.o relNode.o visitor.o
	g++ main.o argsNode.o assignmentNode.o astNode.o Binding.o codeNode.o customAST.o decNode.o fnCallNode.o fnDecNode.o func.o identifierNode.o ifNode.o Interpreter.o intNode.o opNode.o printNode.o programNode.o relNode.o visitor.o -o Smurf.exe

main.o: main.cpp
	g++ -c main.cpp

argsNode.o: argsNode.cpp argsNode.h
	g++ -c argsNode.cpp

assignmentNode.o: assignmentNode.cpp assignmentNode.h
	g++ -c assignmentNode.cpp

astNode.o: astNode.cpp astNode.h
	g++ -c astNode.cpp

Binding.o: Binding.cpp Binding.h
	g++ -c Binding.cpp

codeNode.o: codeNode.cpp codeNode.h
	g++ -c codeNode.cpp

customAST.o: customAST.cpp customAST.h
	g++ -c customAST.cpp

decNode.o: decNode.cpp decNode.h
	g++ -c decNode.cpp

fnCallNode.o: fnCallNode.cpp fnCallNode.h
	g++ -c fnCallNode.cpp

fnDecNode.o: fnDecNode.cpp fnDecNode.h
	g++ -c fnDecNode.cpp

func.o: func.cpp func.h
	g++ -c func.cpp

identifierNode.o: identifierNode.cpp identifierNode.h
	g++ -c identifierNode.cpp

ifNode.o: ifNode.cpp ifNode.h
	g++ -c ifNode.cpp

Interpreter.o: Interpreter.cpp Interpreter.h
	g++ -c Interpreter.cpp

intNode.o: intNode.cpp intNode.h
	g++ -c intNode.cpp

opNode.o: opNode.cpp opNode.h
	g++ -c opNode.cpp

printNode.o: printNode.cpp printNode.h
	g++ -c printNode.cpp

programNode.o: programNode.cpp programNode.h
	g++ -c programNode.cpp

relNode.o: relNode.cpp relNode.h
	g++ -c relNode.cpp

visitor.o: visitor.cpp visitor.h
	g++ -c visitor.cpp